<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Click_Jumlah1</name>
   <tag></tag>
   <elementGuidId>78be314f-f0db-4e75-8109-8a29759b714a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[1]/fuse-root[1]/fuse-main[1]/mat-sidenav-container[1]/mat-sidenav-content[1]/div[1]/div[1]/div[1]/fuse-content[1]/app-package-products-create[1]/div[1]/div[1]/div[1]/form[1]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/mat-list[1]/div[2]/div[1]/mat-list-item[1]/div[1]/div[3]/div[3]/mat-form-field[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/fuse-root[1]/fuse-main[1]/mat-sidenav-container[1]/mat-sidenav-content[1]/div[1]/div[1]/div[1]/fuse-content[1]/app-package-products-create[1]/div[1]/div[1]/div[1]/form[1]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/mat-list[1]/div[2]/div[1]/mat-list-item[1]/div[1]/div[3]/div[3]/mat-form-field[1]</value>
   </webElementProperties>
</WebElementEntity>
