<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_Nama_Product1</name>
   <tag></tag>
   <elementGuidId>0ca8aa31-21fe-4d78-ac38-58e661ad05c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[1]/div[3]/div[2]/div[1]/div[1]/div[1]/ngx-mat-select-search[1]/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[3]/div[2]/div[1]/div[1]/div[1]/ngx-mat-select-search[1]/div[1]</value>
   </webElementProperties>
</WebElementEntity>
